import { Game, ItemListing } from './types';

export const POPULAR_GAMES: Game[] = [
  { id: 'lineage-m', name: '리니지M', icon: '🏰' },
  { id: 'odin', name: '오딘: 발할라 라이징', icon: '⚔️' },
  { id: 'night-walker', name: '나이트 워커', icon: '🌑' },
  { id: 'maplestory', name: '메이플스토리', icon: '🍁' },
  { id: 'lost-ark', name: '로스트아크', icon: '⚓' },
  { id: 'lineage-2m', name: '리니지2M', icon: '🛡️' },
  { id: 'archeage-war', name: '아키에이지 워', icon: '🏹' },
  { id: 'rom', name: 'ROM: 리멤버 오브 마제스티', icon: '👑' },
];

export const MOCK_LISTINGS: ItemListing[] = [
  {
    id: '1',
    gameId: 'lineage-m',
    server: '데포로쥬01',
    title: '[S급] 88레벨 기사 전변/전인 풀스펙 계정 급처합니다',
    price: 4500000,
    thumbnail: 'https://picsum.photos/seed/lineage1/400/300',
    safetyGrade: 'S',
    sellerId: 'user1',
    sellerName: '안전거래왕',
    sellerRating: 4.9,
    sellerTrades: 124,
    isVerified: true,
    description: '1대 본주입니다. 모든 서류 구비 완료. 깔끔하게 넘겨드립니다.',
    level: 88,
    class: '기사',
    equipment: ['+9 뇌신검', '+7 무관의 갑옷', '+5 용사의 반지'],
    skills: ['쇼크 스턴(마스터)', '카운터 배리어'],
    currency: '10,000 다이아 보유',
    images: [
      'https://picsum.photos/seed/lineage1-1/800/600',
      'https://picsum.photos/seed/lineage1-2/800/600',
      'https://picsum.photos/seed/lineage1-3/800/600',
    ],
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: '2',
    gameId: 'odin',
    server: '오딘05',
    title: '전설 탈것 보유 75레벨 스나이퍼 몸계정 판매',
    price: 1200000,
    thumbnail: 'https://picsum.photos/seed/odin1/400/300',
    safetyGrade: 'A',
    sellerId: 'user2',
    sellerName: '게임매니아',
    sellerRating: 4.7,
    sellerTrades: 45,
    isVerified: true,
    description: '재판매 계정입니다. 2대주이며 회수 시 200% 보상 약속합니다.',
    level: 75,
    class: '스나이퍼',
    equipment: ['전설 활', '영웅 방어구 세트'],
    skills: ['화살 비', '집중 사격'],
    currency: '5,000 다이아',
    images: [
      'https://picsum.photos/seed/odin1-1/800/600',
    ],
    createdAt: '2024-03-05T11:30:00Z',
  },
  {
    id: '3',
    gameId: 'night-walker',
    server: '바르바토스',
    title: '나이트 워커 고스펙 계정 정리합니다',
    price: 850000,
    thumbnail: 'https://picsum.photos/seed/nightwalker1/400/300',
    safetyGrade: 'B',
    sellerId: 'user3',
    sellerName: '워커홀릭',
    sellerRating: 4.5,
    sellerTrades: 12,
    isVerified: false,
    description: '개인 사정으로 급하게 정리합니다. 쿨거래 시 네고 가능.',
    level: 100,
    class: '블레이드',
    equipment: ['신화 무기', '전설 방어구'],
    skills: ['궁극기 만렙'],
    currency: '1억 골드',
    images: [
      'https://picsum.photos/seed/nightwalker1-1/800/600',
    ],
    createdAt: '2024-03-05T12:00:00Z',
  },
];
